SolaceDev/solace-dev-codelabs

codelabs/solace-battleship/codelab.json
codelabs/solace-battleship/index.html
codelabs/solace-workshop-scs-pcf/codelab.json
codelabs/solace-workshop-scs/codelab.json
markdown/solace-battleship/codelab.md
markdown/solace-workshop-scs-pcf/solace-workshop-scs-pcf.md
markdown/solace-workshop-scs/solace-workshop-scs.md

Add Solace category to codelabs & workshop tag to battleship

Add Solace category to codelabs & workshop tag to battleship

---

codelabs/solace-k8s-operator/codelab.json
codelabs/solace-k8s-operator/index.html
markdown/solace-k8s-operator/solace-k8s-operator.md

Initial commit of Solace Kubernetes Operator

Initial commit of Kubernetes Operator

---

codelabs/solace-k8s-operator/codelab.json
codelabs/solace-k8s-operator/index.html
markdown/solace-k8s-operator/solace-k8s-operator.md

Kubernetes Operator (#29)

---

codelabs/design-to-code-workshop/codelab.json
codelabs/design-to-code-workshop/index.html
markdown/design-to-code-workshop/design-to-code-workshop.md

Lesson learned; use a specific version!

Add specific asyncapi generator version

---

codelabs/solace-k8s-operator/codelab.json
codelabs/solace-k8s-operator/index.html
markdown/solace-k8s-operator/solace-k8s-operator.md

Updated to support operator-framework 1.0.0 which has significant re-work as it is the first step to merging operator-framework with kubebuilder

Updated to support operator-framework 1.0.0

---

codelabs/exploring-solace-native-apis/codelab.json
codelabs/exploring-solace-native-apis/index.html
markdown/exploring-solace-native-apis/exploring-solace-native-apis.md

Simple change in markdown from the name "PubSub+ Manager" to "PubSub+ Broker Manager", requested by Sarah Diguer.

Changed name of PubSub+ Manager to PubSub+ Broker Manager

---

codelabs/mulesoft-connector/codelab.json
codelabs/mulesoft-connector/index.html
markdown/mulesoft-connector/mulesoft-connector.md

Minor edits to Mulesoft Codelab

Minor edits to MuleSoft Codelab

---

codelabs/design-to-code-workshop/codelab.json
codelabs/design-to-code-workshop/index.html
markdown/design-to-code-workshop/design-to-code-workshop.md

Remove actuator parameter to simplify asyncapi gen command and avoid port conflicts when running app w/ docker container.

Remove actuator to simplify

---

codelabs/solace-workshop-scs-pcf/codelab.json
codelabs/solace-workshop-scs-pcf/index.html
codelabs/solace-workshop-scs/codelab.json
codelabs/solace-workshop-scs/index.html
markdown/solace-workshop-scs-pcf/solace-workshop-scs-pcf.md
markdown/solace-workshop-scs/solace-workshop-scs.md

Add deprecation warnings for Cloud Stream Codelabs that use Annotation based code.

Add deprecation warnings

---

codelabs/design-to-code-workshop/codelab.json
codelabs/design-to-code-workshop/index.html
markdown/design-to-code-workshop/design-to-code-workshop.md

Update Design to Code Workshop: Big Decimal Changes

Update Design to Code Workshop: Big Decimal Changes

---

codelabs/azure2Solace/codelab.json
codelabs/azure2Solace/index.html
markdown/azure2Solace/azure2Solace.md

Fix broken link in Azure Codelab + update feedback link to go to markdown

Fix broken link in Azure Codelab

---

codelabs/spring-cloud-stream-beyond/codelab.json
codelabs/spring-cloud-stream-beyond/index.html
markdown/spring-cloud-stream-beyond/spring-cloud-stream-beyond.md

Fix yaml in Beyond Basics Codelab

Fix yaml in Beyond Basics Codelab

---

codelabs/spring-cloud-stream-beyond/codelab.json
codelabs/spring-cloud-stream-beyond/index.html
markdown/spring-cloud-stream-beyond/spring-cloud-stream-beyond.md

Add video link for all about solace topics!

Add video link for all about solace topics!

---

codelabs/design-document-discover-develop-event-driven-apis/codelab.json
codelabs/design-document-discover-develop-event-driven-apis/index.html
codelabs/ep-discovery-kafka/codelab.json
codelabs/ep-discovery-kafka/index.html
markdown/design-document-discover-develop-event-driven-apis/design-document-discover-develop-event-driven-apis.md
markdown/ep-discovery-kafka/ep-discovery-kafka.md

* Mark codelab as hidden, but keep so links don't break
* Add warning at the top of each page in case folks still find it
* Fix link in Design Document Code codelab to point to Solace docs

Hide Kafka Discovery Codelab

---

codelabs/design-to-code-workshop/index.html
codelabs/keda-solace-queue/index.html
markdown/design-to-code-workshop/design-to-code-workshop.md
markdown/keda-solace-queue/keda-solace-queue.md

* Fix #140 
* Fix Broken KEDA Link

Quick Fixes

---

markdown/Boomi-request-reply/Boomi-request-reply.md

Some typo fixes and minor wording changes.  Submitted as separate commits so you can pick and choose.

Minor fixes

---

codelabs/design-document-discover-develop-event-driven-apis/codelab.json
codelabs/design-document-discover-develop-event-driven-apis/index.html
markdown/design-document-discover-develop-event-driven-apis/design-document-discover-develop-event-driven-apis.md

Fixed the instruction, and explanation around the ProcessPayment application (uses Spring binder) and InvoiceSystem (uses NodeJS binder) - should be ok now! Needs a quick run of the instructions.

Design document discover event driven apis

---

markdown/keda-solace-queue/keda-solace-queue.md

from docs/2.7 to docs/2.8
for current release of keda

update keda.sh site links in code lab

---

codelabs/helm-environment-setup/index.html
markdown/solace-helm-environment-setup/helm-environment-setup.md

Correcting a small typo in a section heading, where "help" was used where "helm" seemed clearly meant.

Correct typo

---

codelabs/solace-battleship/codelab.json
markdown/solace-battleship/solace-battleship.md

Hiding Battleship Codelab as the Udemy course was deleted previously.

Hide Battleship Codelab

---

markdown/ep-connect-ep-broker/ep-connect-ep-broker.md
markdown/ep-lifecycle/ep-lifecycle.md

some feedback from Dishant and Phil

added podman instructions

---

markdown/ep-connect-ep-broker/ep-connect-ep-broker.md

Fixing minor typos in the ep-connect-ep-broker codelab.

Fixing minor typos.
